import SwiftUI

struct WatermarkPattern: View {
    let text: String
    
    var body: some View {
        GeometryReader { geometry in
            let width = geometry.size.width
            let height = geometry.size.height
            let rows = Int(height / 100) + 2
            let cols = Int(width / 150) + 2
            
            VStack(spacing: 60) {
                ForEach(0..<rows, id: \.self) { _ in
                    HStack(spacing: 40) {
                        ForEach(0..<cols, id: \.self) { _ in
                            Text(text)
                                .font(.system(size: 20, weight: .bold))
                                .foregroundColor(.white)
                                .opacity(0.15)
                                .rotationEffect(.degrees(-45))
                                .fixedSize()
                        }
                    }
                }
            }
            .frame(width: width, height: height, alignment: .center)
            .clipped()
            .allowsHitTesting(false)
        }
    }
}

struct ExportableStoryView: View {
    let storyContent: String
    
    var body: some View {
        ZStack {
            Color(hex: "1a1a2e")
            
            Text(storyContent)
                .font(.custom("Georgia", size: 18))
                .foregroundColor(.white)
                .padding(40)
                .multilineTextAlignment(.leading)
            
            WatermarkPattern(text: "Dreamweaver Stories")
            
            VStack {
                Spacer()
                HStack {
                    Spacer()
                    Text("Generated by Dreamweaver")
                        .font(.caption)
                        .foregroundColor(.white.opacity(0.5))
                        .padding()
                }
            }
        }
        .frame(width: 500, height: 800)
    }
}
